name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Check test status
        run: |
          pytest --exitfirst
          test_status=$?

          if [ $test_status -ne 0 ]; then
            echo "Los tests de FastAPI no se ejecutaron correctamente. No se permite hacer push."
            exit 1
          fi

